server:
  port: 80
  context-path: /areaDemo
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://******:3306/mysql_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://******:3306/mysql_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root
mybatis:
    entityPackage:  com.area.areademo.entity
    mapperPath:  /mybatis/**.xml
    mybatisConfigFilePath: mybatis-config.xml


